### ISSUE TITLE
Background color not reset in Kitty

### ISSUE THREAD

**Issue by blinry** [typicode/bg.nvim#14]
Hey :) I updated the plugin today, from previously 61e1150, and now the background color is no longer reset when I close Neovim. So I assume #12 must have introduced this regression (pinging @violetfauna).

I'm using Kitty 0.37.0 and Neovim 0.10.2. And the [melange](https://github.com/savq/melange-nvim) color scheme, loading both via Lazy. What could I try to help test or fix this?

**Comment by violetfauna** [comment]
so i'm unsure if this is the exact issue that you had, but it's probably because i wasn't popping the stack enough to account for if neovim changed colors more than once.

i pushed a fix [here](https://github.com/violetfauna/bg.nvim), and hopefully that resolves it if you want to try. i tested this local configuration (below), and it seems to be working now.
```lua
-- init.lua
-- Bootstrap lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  local lazyrepo = "https://github.com/folke/lazy.nvim.git"
  local out = vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
  if vim.v.shell_error ~= 0 then
    vim.api.nvim_echo({
      { "Failed to clone lazy.nvim:\n", "ErrorMsg" },
      { out, "WarningMsg" },
      { "\nPress any key to exit..." },
    }, true, {})
    vim.fn.getchar()
    os.exit(1)
  end
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  spec = {
    {
      "savq/melange-nvim",
      "violetfauna/bg.nvim"
    },
  },
  install = { colorscheme = { "melange" } },
})

vim.cmd.colorscheme 'melange'

```

**Comment by blinry** [comment]
I tried it, and it helps! :tada: Thanks, I'd love it if you'd make a PR!
